title: Miyuru Thathsara
description: Miyuru Thathsara develops embedded intelligence and hardware acceleration to help robots understand their surroundings, working toward collaborative autonomy.
url: "https://miyuruthathsara.github.io"
baseurl: ""
lang: en
personal_website: "https://miyuruthathsara.com"
scholar_url: "https://scholar.google.com/citations?user=_F2z9wYAAAAJ&hl=en"
linkedin_url: "https://lk.linkedin.com/in/miyuru-thathsara-07596518b"
github_url: "https://github.com/MiyuruThathsara"
university_email: "miyuruth001@e.ntu.edu.sg"
personal_email: "mthathsara@outlook.com"

exclude:
  - changes.md
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - package.json
  - package-lock.json
  - tests
